baseURL = 'https://fedang.net'
languageCode = 'en-us'
title = '~fedang'

theme = 'chilldark'

enableRobotsTXT = true

[params.author]
	name = "Federico Angelilli"

[params]
	bottom_text = "**🅭** [BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

[security]
  enableInlineShortcodes = true
