baseURL = 'https://fedang.net'
languageCode = 'en-us'
title = '~fedang'
theme = 'chilldark'
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
copyright = "Federico Angelilli © 2025"

[taxonomies]
	category = 'categories'
	tag = 'tags'
	series = 'series'


[outputs]
	home = ['html', 'rss']
	section = ['html']
	taxonomy = ['html']
	term = ['html']

[frontmatter]
  date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', ':git']
  lastmod = [':git', 'lastmod', 'date', 'publishdate' ]
  publishDate = ['publishdate', 'published', 'date']

[params.author]
	name = "Federico Angelilli"
	email = "main@fedang.net"

[params]
	title_crumbs = false
	bottom_text = "Federico Angelilli {{< dash >}} [BY-NC-SA 4.0]({{% ref license %}}) [{{< icon creative-commons small >}}](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
	custom_css = ["css/syntax.css"]

[security]
  enableInlineShortcodes = true

[markup]
  [markup.highlight]
	noClasses = false
  [markup.goldmark.renderer]
	unsafe = true
